version: '3'

services:
  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      TZ: 'Asia/Tokyo'
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 3031:3031
    command: ['npm', 'run', 'start']
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
    restart: always
    depends_on:
      - db
